---
title: "Area charts"
author: "Haley Jeppson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(tidyverse)
```

Set-up:

```{r}
# devtools::install_github("ijlyttle/altair")
library("altair")

vega_data <- import_vega_data()
```


#### Horizon Graph

```{r}

df = jsonlite::fromJSON('[
      {"x": 1,  "y": 28}, {"x": 2,  "y": 55},
      {"x": 3,  "y": 43}, {"x": 4,  "y": 91},
      {"x": 5,  "y": 81}, {"x": 6,  "y": 53},
      {"x": 7,  "y": 19}, {"x": 8,  "y": 87},
      {"x": 9,  "y": 52}, {"x": 10, "y": 48},
      {"x": 11, "y": 24}, {"x": 12, "y": 49},
      {"x": 13, "y": 87}, {"x": 14, "y": 66},
      {"x": 15, "y": 17}, {"x": 16, "y": 27},
      {"x": 17, "y": 68}, {"x": 18, "y": 16},
      {"x": 19, "y": 49}, {"x": 20, "y": 15}
    ]')

area1 = alt$Chart(r_to_py(df))$mark_area(
    clip=TRUE,
    interpolate='monotone'
)$encode(
    alt$X('x', scale=alt$Scale(zero=FALSE, nice=FALSE)),
    alt$Y('y', scale=alt$Scale(domain=list(0, 50)), axis=alt$Axis(title='y')),
    opacity=alt$value(0.6)
)$properties(
    width=500,
    height=75
)

area2 = area1$encode(
    alt$Y('ny:Q', scale=alt$Scale(domain=list(0, 50)))
)$transform_calculate(
    "ny", 'datum.y - 50'
)

vegalite(area1 + area2)

```

#### Interval Selection Example

```{r}
brush = alt$selection(type = "interval", encodings = list("x"))

upper = alt$Chart()$mark_area()$encode(
    alt$X('date:T', scale=list('domain'= brush$ref())),
    y='price:Q'
)$properties(
    width=600,
    height=200
)

lower = upper$properties(
    selection=brush,
    height=60
)

plot <- alt$vconcat(upper, lower, data= r_to_py(sp500))

vegalite(plot)
```

#### Streamgraph

```{r}
source = r_to_py(vega_data$unemployment_across_industries())

plot <- alt$Chart(source)$mark_area()$encode(
    alt$X('date:T',
        timeUnit='yearmonth',
        axis=alt$Axis(format='%Y', domain=FALSE, tickSize=0)
    ),
    alt$Y('sum(count):Q', stack='center', axis=NULL),
    alt$Color('series:N',
        scale=alt$Scale(scheme='category20b')
    )
)$interactive()

vegalite(plot)
```

#### Trellis Area

```{r}

source = r_to_py(vega_data$stocks())

plot <- alt$Chart(source)$mark_area()$encode(
    alt$X('date:T', axis=alt$Axis(format='%Y', title='Time', grid=FALSE)),
    alt$Y('price:Q', axis=alt$Axis(title='Price', grid=FALSE)),
    alt$Color('symbol', legend=NULL),
    alt$Row('symbol:N', header=alt$Header(title='Symbol'))
)$properties(
    width=300,
    height=40
)$transform_filter(
    "datum.symbol != 'GOOG'"
)

vegalite(plot)
```






