---
title: "Field Guide to Rendering Charts"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
editor_options:
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

There are four foundations upon which this package rests: 

- the [Altair](https://altair-viz.github.io/) Python package, to build chart specifications
- the [reticulate](https://rstudio.github.io/reticulate/index.html) R package, to provide inter-operability with Python
- the [Vega-Lite](https://vega.github.io/vega-lite/) JavaScript framework, to render chart specifications in an HTML file
- the [vegawidget](https://vegawidget.github.io) R package, which relies on [htmlwidgets](https://www.htmlwidgets.org/) to provide inter-operability with HTML and JavaScript

This article deals with the second two items; the [Field Guide to Python Issues](field-guide-python.html) deals with the first two.

## Vegawidget

All the rendering is handled by **vegawidget**; so you are referred to its article on [rendering](https://vegawidget.github.io/vegawidget/articles/articles/render-vegawidget.html).

The two main issues on rendering are:

- sizing
- arguments passed to [vega-embed](https://github.com/vega/vega-embed) (more specialized)

These are discussed in these sections of the vegawidget rendering-article:

- [Using vegawidget arguments](https://vegawidget.github.io/vegawidget/articles/articles/render-vegawidget.html#using-vegawidget-arguments), calling the `vegawidget()` function
- [Setting R options](https://vegawidget.github.io/vegawidget/articles/articles/render-vegawidget.html#setting-r-options), can be set a number of ways
- [Knitting strategies](https://vegawidget.github.io/vegawidget/articles/articles/render-vegawidget.html#knitting-strategies), including how to render Vega(-Lite) charts when knitting to a non-HTML format such as PDF

## Rendering speed for interactive work

This section applies to *interactive* work; it does not apply to RMarkdown documents.

Rather than embed the data itself into the chart spec as JSON (this will become very slow as the data gets to be more than 5000 rows), Altair has an option (supported by Vega-Lite's URL loader) that saves your data as a JSON file that is referenced in the chart spec. 

Keep in mind that this will work only for interactive (non-knitting) work. In Python you would set `alt.data_transformers.enable('json')`; in R this becomes:

```r
library("altair")
alt$data_transformers$enable('json')
```

The problem is that you won't see charts in the RStudio pane anymore. This won't work:

```r
vega_data <- import_vega_data()

chart <- 
     alt$Chart(vega_data$cars())$
     mark_point()$
     encode(
         x = "Horsepower:Q",
         y = "Miles_per_Gallon:Q",
         color = "Origin:N",
         tooltip = c("Name", "Horsepower", "Miles_per_Gallon", "Origin")
     )

chart
```

This calls the print method on chart, which runs `vegawidget(chart)`; instead, you need to tell `vegawidget()` where it can expect your external file. 

You have a couple of choices here:

- you can call `vegawidget()` supplying a value for `base_url`:

  ```r
  vegawidget(chart, base_url=".")
  ```

- **or** you can set the `base_url` *once* for your session using:

  ```r
  vw_set_base_url(".")
  ```
  
  then, this should *just work* interactively:

  ```r
  chart
  ```

Keep in mind that by using `alt$data_transformers$enable("json")`, **all** charts you create subsequently will write out data files until:

- you restart R.
- you enable a different transformer, e.g `alt$data_transformers$enable("default")`.

Altair's documentation has a [page dedicated to data transformers](https://altair-viz.github.io/user_guide/data_transformers.html).



