---
title: "Field Guide to Python Issues"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
editor_options:
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

There are four foundations upon which this package rests: 

- the [Altair](https://altair-viz.github.io/) Python package, to build chart specifications
- the [reticulate](https://rstudio.github.io/reticulate/index.html) R package, to provide inter-operability with Python
- the [Vega-Lite](https://vega.github.io/vega-lite/) JavaScript framework, to render chart specifications in an HTML file.
- the [htmlwidgets](https://www.htmlwidgets.org/) R package, to provide inter-operability with HTML and JavaScript

This article deals with the first two items; the [rendering article](render.html) deals with the other two.

The purpose of this document is to try to collect in one place, in a semi-organized fashion, all the fiddly-bits we have found dealing with Python stuff. This includes:

* [**Proxies and certificates**](#proxies): letting your computer know how to communicate with the world
* [**Python installation**](#python): installing Python
* [**Python environment**](#python-env): setting up a Python environment with a "standard" name
* [**Altair installation**](#altair): installing Altair into your Python environment
* [**Working with Python objects**](#work-work): how to work with Altair and Vega-datasets objects
* [**Odds and ends**](#odds-ends): weird bits that don't fit anywhere else

To be clear, there is a bit of hassle to set-up Python to use your first R-package that uses reticulate.  Getting to this point is the focus of the first three sections of this document.

Thanks to the folks at RStudio, once you have a Python environment set up in a standard way, each subsequent installation is a single command-line call in addition to installing the R package. This is the focus of the [**Altair installation**](#altair) section, to which you can skip if you already have a working Python (Conda recommended) environment called `"r-reticulate"`.

## Proxies and certificates {#proxies}

This first step is the most bothersome; you may need to collect some information on certificates (and proxies, if you work behind a firewall), then distribute that infomation to different places on your computer:

- location of a valid certificate file: `</path/to/your/certificate/file.crt>`

Additionally, if you work behind a firewall:

- address of your proxy: `http://<your.proxy.ip.address>:<port>`
- list of addresses for which your proxy is not to be used: `127.0.0.1,localhost,<other.hostnames.go.here>`

Please note that the angle-brackets , `<>`, are a quoting mechanism for demonstration; they should not be a part of your variables.

If you do not work behind a firewall, you need only determine the location of a valid certificate file. If you have the **httr** package installed, it will use the certificate file associated with the **openssl** package. You can determine the location of this certificate file by using:

```r
system.file("cacert.pem", package = "openssl")
```

At this point, you can note this location and move ahead to [**Managing your settings**](#manage-settings).

### Working behind a firewall

If you work behind a firewall, it may be a little trickier to find your certificate file. Sylvain Marié has put together a field-guide called [develop-behind-proxy](https://smarie.github.io/develop-behind-proxy/), from which we take some inspiration. 

It is possible that your IT department requires that your certificate bundle be modified to include a certificate that your IT department can use to monitor your traffic. In this case, Sylvain offers [some advice](https://smarie.github.io/develop-behind-proxy/know_your_proxy/) to find this certificate bundle, or you can ask your IT department for its location.

Your proxy is likely set using environment variables, named some combination of:

 - `http_proxy`, `https_proxy`, `no_proxy`, `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`

If you are using Windows, your proxy information may be set using your system's environment variables, in which case you may not need to do anything more. 

It is also possible that you use your `.Renviron` file to set your proxy and no-proxy variables. If you have the **usethis** package installed, it can be very easy to find and open: `usethis::edit_r_environ()`.

Once you have noted your proxy and no-proxy settings, as well as the location of a certificate file, you are ready to move on.

### Managing your settings {#manage-settings}

Now that you have your information on your certificate (and proxy), the next step is to make this information known to all the programs on your computer that need it.

#### Windows

#### MacOS

#### Linux

### R settings 

Even though things may already be set up on your computer to use R to access the internet, there are a some things we should set to make it easier for **reticulate** to work with its Python environment. As best as I can tell, when **reticulate** launches its Python, its Python environment inherits environment variables from R. 

Accordingly, we should set some variables in `.Renviron` for this Python environment to use (you may have some of these set already). Add and adapt the following lines as needed. The angle-brackets , `<>`, are a quoting mechanism for demonstration; they should not be a part of your variables.

```
# .Renviron

# path to a certificate file 
SSL_CERT_FILE = "</path/to/your/certificate/file.crt>"
REQUESTS_CA_BUNDLE = "${SSL_CERT_FILE}"

# --------------------------------------
# continue if you work behind a firewall

# proxy addresses
https_proxy = "http://<your.proxy.ip.address>:<port>"
http_proxy = "${https_proxy}" 

HTTPS_PROXY = "${https_proxy}"
HTTP_PROXY = "${http_proxy}"

# addresses for which proxy is not to be used
no_proxy = "127.0.0.1,localhost,<other.hostnames.go.here>"
```

Although you may not yet have set up a Conda environment, this may be a good time to tell **reticulate** which Python environment to use. For use with **reticulate**, RStudio [recommend] using a Python environment called `"r-reticulate"`. If you are using Conda, we recommend that you add this line to your `.Rprofile` (`usethis::edit_r_profile()` can be useful). 

```
# .Rprofile
reticulate::use_condaenv("r-reticulate")
```

Of course, you should restart your R session to let your new settings take effect.

### System settings

To diagnose problems, it can be useful to access Python from your command-line. In this case, Python will need to get its environment variables from the system itself. How to set these, as you can imagine, depends on your system.

#### MacOS

The file `~/.bash_profile` acts in a similar way as `.Renviron`, but the syntax is just a little different. Using your favorite text editor, find and edit your `.bash_profile`, adding and adapting these lines as needed. The angle-brackets , `<>`, are a quoting mechanism for demonstration; they should not be a part of your variables.

```
# MacOS .bash_profile

# path to a certificate file 
export SSL_CERT_FILE=</path/to/your/certificate/file.crt>
export REQUESTS_CA_BUNDLE=${SSL_CERT_FILE}

# --------------------------------------
# continue if you work behind a firewall

# specifies addresses for which proxy is not to be used
export NO_PROXY="127.0.0.1,localhost,<other.hostnames.go.here>"

# specifies the proxy addresses
export https_proxy=http://<your.proxy.ip.address>:<port>
export http_proxy=${https_proxy}

export HTTPS_PROXY=${https_proxy}
export HTTP_PROXY=${http_proxy}
```

A new terminal window will have access to these settings.

#### Windows

In Windows, the customary way to set or change environment variables is to use `Control Panel\All Control Panel Items\System` then "Advanced System Settings" and "Environment Variables". This may vary according to your version of Windows. I would set each of these variables to values, adapting these lines as needed. The angle-brackets , `<>`, are a quoting mechanism for demonstration; they should not be a part of your variables.

```
# Windows environment variables
# 
# Varaible : Value

SSL_CERT_FILE : </path/to/your/certificate/file.crt>
REQUESTS_CA_BUNDLE: </path/to/your/certificate/file.crt>

# --------------------------------------
# continue if you work behind a firewall

NO_PROXY : 127.0.0.1,localhost,<other.hostnames.go.here>

HTTP_PROXY : http://<your.proxy.ip.address>:<port>
HTTPS_PROXY : http://<your.proxy.ip.address>:<port>
```


## Python {#python}

We recommend (until its next CRAN release) using the dev version of **reticulate**:

```r
# install.packages("devtools")
devtools::install_github("rstudio/reticulate")
```

Reticulate offers a number of ways to manange the installation of Python packages into a Python environment, as described in its [*Installing Python Packages*](https://rstudio.github.io/reticulate/articles/python_packages.html) article.

Here, we amplify some opinions adapted from RStudio. Because [Conda](https://conda.io/docs/) is available for Windows, MacOS, and Linux, we recommend using a Conda Python installation. I have found using that using Conda for Python 3.6 works well.

Follow the [Conda installation instructions](https://conda.io/docs/user-guide/install/index.html) to suit your particular situation. You will have the choice to install Conda or Miniconda. I have found that both work; the choice depends on how many Python packages you wish to install right away.


Close out of your system-settings window and open an "Anaconda prompt". If all is well, you will be able to update your Conda installation:

```
# Anaconda prompt

conda update conda
```

## Python environment {#python-env}

Once you have Conda installed, and you are able to successfully update it from the Conda prompt (`conda update conda`), create a Conda environment called `"r-reticulate"`. 

One way to do this is from an R command-prompt:

```r
reticulate::conda_create("r-reticulate")
```

This should "just work".

## Altair Installation {#altair}

## Working with Python objects {#work-work}

### Altair object

### Vega-datasets object

## Odds and ends {#odds-ends}

### Dots in variables
