---
title: "Simple charts"
author: "Haley Jeppson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(tidyverse)
```

Set-up:

```{r}
# devtools::install_github("ijlyttle/altair")
library("altair")

vega_data <- import_vega_data()
```


#### Simple Bar Chart

```{r}

dat = data_frame(a= c('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'),
    b =c(28, 55, 43, 91, 81, 53, 19, 87, 52))

plot <- 
  alt$Chart(
    r_to_py(dat)
  )$mark_bar(
  )$encode(
    x = "a",
    y = "b"
  )

vegalite(plot)
```

#### Simple Heatmap

```{r}
# Compute x^2 + y^2 across a 2D grid
x = -5:5
y = -5:5
dat <- expand.grid(x,y)
names(dat) <- c("x", "y")
dat$z = (dat$x^2) + (dat$y^2)


plot <- 
  alt$Chart(
    r_to_py(dat)
  )$mark_rect(
  )$encode(
    x='x:O',
    y='y:O',
    color='z:Q'
)

vegalite(plot)
```


#### Simple Histogram

Had to replace `y = "count()"` with `y = "count(IMDB_Rating)"`

```{r}

plot <- 
  alt$Chart(
    r_to_py(vega_data$movies())
  )$mark_bar(
  )$encode(
    alt$X("IMDB_Rating", bin = TRUE), 
    y = "count(IMDB_Rating)"
  )

vegalite(plot)
```



#### Simple Line Chart

```{r}
dat <- data_frame(x = 0:100) 
dat$sinx <- sin(dat$x / 5)

plot <- 
  alt$Chart(
    r_to_py(dat)
  )$mark_line(
  )$encode(
    x='x',
    y='sinx'
)


vegalite(plot)
```

#### Simple Scatter Plot

```{r}
plot <- 
  alt$Chart(
    r_to_py(vega_data$iris())
  )$mark_point(
  )$encode(
   x='petalWidth',
    y='petalLength',
    color='species'
)$interactive()

vegalite(plot)
```

#### Simple Stacked Area Chart

```{r}
plot <- 
  alt$Chart(
    r_to_py(vega_data$unemployment_across_industries())
  )$mark_area(
  )$encode(
    x="date:T",
    y="count:Q",
    color="series:N"
)

vegalite(plot)
```


#### Strip Plot

```{r}
plot <- 
  alt$Chart(
    r_to_py(vega_data$cars())
  )$mark_tick(
  )$encode(
    x='Horsepower:Q',
    y='Cylinders:O'
)

vegalite(plot)
```







