---
title: "Line Charts"
author: "Haley Jeppson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(tidyverse)
```

Set-up:

```{r}
# devtools::install_github("ijlyttle/altair")
library("altair")

vega_data <- import_vega_data()
```

#### Cumulative Wikipedia Donations

```{r}
data <- read_csv(curl::curl("https://frdata.wikimedia.org/donationdata-vs-day.csv"))

plot <- alt$Chart(r_to_py(data))$mark_line()$encode(
    alt$X(
        'date:T', timeUnit='monthdate',
        axis=alt$Axis(format='%B', title='Month')
    ),
    alt$Y(
        'max(ytdsum):Q', stack=NULL,
        axis=alt$Axis(title='Cumulative Donations')
    ),
    alt$Color('date:O', timeUnit='year', legend=alt$Legend(title='Year')),
    alt$Order('data:O', timeUnit='year')
)

vegalite(plot)
```

#### Falkensee

```{r, echo = FALSE}

source = jsonlite::fromJSON('[
      {"year": "1875", "population": 1309},
      {"year": "1890", "population": 1558},
      {"year": "1910", "population": 4512},
      {"year": "1925", "population": 8180},
      {"year": "1933", "population": 15915},
      {"year": "1939", "population": 24824},
      {"year": "1946", "population": 28275},
      {"year": "1950", "population": 29189},
      {"year": "1964", "population": 29881},
      {"year": "1971", "population": 26007},
      {"year": "1981", "population": 24029},
      {"year": "1985", "population": 23340},
      {"year": "1989", "population": 22307},
      {"year": "1990", "population": 22087},
      {"year": "1991", "population": 22139},
      {"year": "1992", "population": 22105},
      {"year": "1993", "population": 22242},
      {"year": "1994", "population": 22801},
      {"year": "1995", "population": 24273},
      {"year": "1996", "population": 25640},
      {"year": "1997", "population": 27393},
      {"year": "1998", "population": 29505},
      {"year": "1999", "population": 32124},
      {"year": "2000", "population": 33791},
      {"year": "2001", "population": 35297},
      {"year": "2002", "population": 36179},
      {"year": "2003", "population": 36829},
      {"year": "2004", "population": 37493},
      {"year": "2005", "population": 38376},
      {"year": "2006", "population": 39008},
      {"year": "2007", "population": 39366},
      {"year": "2008", "population": 39821},
      {"year": "2009", "population": 40179},
      {"year": "2010", "population": 40511},
      {"year": "2011", "population": 40465},
      {"year": "2012", "population": 40905},
      {"year": "2013", "population": 41258},
      {"year": "2014", "population": 41777}
    ]')


source2 = jsonlite::fromJSON( '[{
            "start": "1933",
            "end": "1945",
            "event": "Nazi Rule"
          },
          {
            "start": "1948",
            "end": "1989",
            "event": "GDR (East Germany)"
          }]')

source = r_to_py(source)
source2 = r_to_py(source2)

```

```{r}

line = alt$Chart(source)$mark_line(color='#333')$encode(
    alt$X('year:T', axis=alt$Axis(format='%Y')),
    y='population'
)$properties(
    width=600,
    height=400
)

point = line$mark_point(color='#333')

rect = alt$Chart(source2)$mark_rect()$encode(
    x='start:T',
    x2='end:T',
    color='event:N'
)

vegalite(rect + line + point)
```

#### Line Chart with Layered Aggregates

```{r}
stocks = r_to_py(vega_data$stocks())

line = alt$Chart(stocks)$mark_line()$encode(
    x='date',
    y='price',
    color='symbol'
)$properties(
    width=600,
    title="Daily closing prices with their aggregate prices"
)$interactive(bind_y=FALSE)

rule = alt$Chart(stocks)$mark_rule()$encode(
    alt$Y('average(price)'),
    color='symbol',
    size=alt$value(2)
)

vegalite(line + rule)
```

#### Line Chart with Percent axis

```{r}
jobs <- vega_data$jobs()
jobs <- jobs %>% sample_n(5000)

source = r_to_py(jobs)

plot <- alt$Chart(source)$mark_line()$encode(
    alt$X('year:O'),
    alt$Y('perc:Q', axis=alt$Axis(format='%')),
    color='sex:N'
)$properties(
    title='Percent of work-force working as Welders'
)$transform_filter(
    "datum.job == 'Welder'"
)

vegalite(plot)
```

#### Line chart with Confidence Interval Band

```{r}

cars = r_to_py(vega_data$cars())

line = alt$Chart(cars)$mark_line()$encode(
    x='Year',
    y='mean(Miles_per_Gallon)'
)

confidence_interval = alt$Chart(cars)$mark_area(opacity=0.3)$encode(
    x='Year',
    y=alt$Y('ci0(Miles_per_Gallon)', axis=alt$Axis(title='Miles/Gallon')),
    y2='ci1(Miles_per_Gallon)'
)

vegalite(confidence_interval + line)
```

#### Multi Series Line Chart

Had to make sure to delare that the `date` variable tis of type `"temporal"`

```{r}
plot <- 
  alt$Chart(
    r_to_py(vega_data$stocks())
  )$mark_line(
  )$encode(
    x='date:T',
    y='price',
    color='symbol'
  )

vegalite(plot)
```

#### Slope Graph

```{r}

# The year here is stored by pandas as an integer. When treating columns as dates,
# it is best to use either a string representation or a datetime representation.
barley <- vega_data$barley()
barley$year <- as.character(barley$year)

source = r_to_py(barley)

plot <- alt$Chart(source)$mark_line()$encode(
    x='year',
    y='median(yield)',
    color='site'
)

vegalite(plot)
```

#### Step Chart

Need to specify the `transform_filter` as a string?

```{r}
plot <- 
  alt$Chart(
    r_to_py(vega_data$stocks())
  )$mark_line(interpolate='step-after'
  )$encode(
    x='date',
    y='price'
  )$transform_filter(
     "datum.symbol == 'GOOG'"
 )


vegalite(plot)
```










