---
title: "Histograms"
author: "Haley Jeppson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(tidyverse)
```


Set-up:

```{r}
# devtools::install_github("ijlyttle/altair")
library("altair")

vega_data <- import_vega_data()
```

#### Histogram with a Global Mean Overlay

```{r}

source = r_to_py(vega_data$movies())

bar = alt$Chart(source)$mark_bar()$encode(
    alt$X('IMDB_Rating:Q', bin=TRUE, axis=NULL),
    alt$Y('count(IMDB_Rating)')
)

rule = alt$Chart(source)$mark_rule(color='red')$encode(
    x='mean(IMDB_Rating):Q',
    size=alt$value(5)
)

vegalite(bar + rule)
```

#### Layered Histogram

```{r}
# Generating Data
df <- data_frame(Trial_A = rnorm(1000, 0, 0.8),
                   Trial_B = rnorm(1000, -2, 1),
                   Trial_C = rnorm(1000, 3, 2))

# Tidying Data
df <- df %>% gather(Experiment, Measurement)
  
plot <- alt$Chart(
  r_to_py(df)
  )$mark_area(
    opacity=0.3,
    interpolate='step'
)$encode(
    alt$X('Measurement', bin=alt$Bin(maxbins=100)),
    alt$Y('count(Measurement)', stack=NULL),
    alt$Color(
        'Experiment',
        scale=alt$Scale(range=list('#0000ff', '#008000', '#ff0000'))
    )
)

vegalite(plot)
```

#### Trellis Histogram


```{r}
plot <- alt$Chart(
  r_to_py(vega_data$cars())
  )$mark_bar()$encode(
    alt$X("Horsepower:Q", bin=TRUE),
    y='count(Horsepower)',
    row='Origin'
)

vegalite(plot)
```

