---
title: "Other Charts"
author: "Haley Jeppson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(tidyverse)
```

Set-up:

```{r}
# devtools::install_github("ijlyttle/altair")
library("altair")

vega_data <- import_vega_data()
```

#### Binned Movie Rating Heatmap

```{r}
plot <- 
  alt$Chart(
    r_to_py(vega_data$movies())
  )$mark_rect(
  )$encode(
    alt$X('IMDB_Rating:Q', bin=alt$Bin(maxbins=60)),
    alt$Y('Rotten_Tomatoes_Rating:Q', bin=alt$Bin(maxbins=40)),
    alt$Color('count(IMDB_Rating):Q', scale=alt$Scale(scheme='greenblue'))
)

vegalite(plot)
```

#### Facetted Scatterplot with marginal histograms

```{r}
iris = r_to_py(vega_data$iris())

xscale = alt$Scale(domain=c(4.0, 8.0))
yscale = alt$Scale(domain=c(1.9, 4.55))

blank_axis = alt$Axis(title='')

points = alt$Chart(iris)$mark_circle()$encode(
    alt$X('sepalLength', scale=xscale),
    alt$Y('sepalWidth', scale=yscale),
    color='species'
)

top_hist = alt$Chart(iris)$mark_area(opacity= .3, interpolate= 'step')$encode(
    alt$X('sepalLength:Q',
          # when using bins, the axis scale is set through
          # the bin extent, so we do not specify the scale here
          # (which would be ignored anyway)
          bin=alt$Bin(maxbins=20, extent=xscale$domain),
          stack=NULL,
          axis=blank_axis
         ),
    alt$Y('count(sepalLength)', stack=NULL, axis=blank_axis),
    alt$Color('species:N')
)$properties(height=60)

right_hist = alt$Chart(iris)$mark_area(opacity= .3, interpolate= 'step')$encode(
    alt$Y('sepalWidth:Q',
          bin=alt$Bin(maxbins=20, extent=yscale$domain),
          stack=NULL,
          axis=blank_axis
         ),
    alt$X('count(sepalWidth)', stack=NULL, axis=blank_axis),
    alt$Color('species:N')
)$properties(width=60)

vegalite(top_hist & (points | right_hist))
```

#### Layering text over a heatmap

```{r}
cars <- r_to_py(vega_data$cars())

heatmap = alt$Chart(cars)$mark_rect()$encode(
    alt$X('Cylinders:O', scale=alt$Scale(paddingInner=0)),
    alt$Y('Origin:O', scale=alt$Scale(paddingInner=0)),
    color='count(Cylinders)'
)

text = alt$Chart(cars)$mark_text(baseline='middle')$encode(
    x='Cylinders:O',
    y='Origin:O',
    text='count(Cylinders)',
    color=alt$condition("datum['count_*'] > 100",
                        alt$value('black'),
                        alt$value('white'))
)

vegalite(heatmap + text)
```

#### Multiple Marks (not working)

```{r, eval = FALSE}
stocks = r_to_py(vega_data$stocks())

plot <- alt$LayerChart(stocks)$encode(
    x='date:T',
    y='price:Q',
    color='symbol:N'
)$add_layers(
    alt$Chart()$mark_point(),
    alt$Chart()$mark_line()
)

vegalite(plot)
```

#### Ranged Dot Plot

#### Steam and Leaf Plot

#### Trail Marker







