---
title: "Other Charts"
author: "Haley Jeppson"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This document is adapted from the [Bar Charts](https://altair-viz.github.io/gallery/index.html#bar-charts) section of the Altair Example Gallery.

Our first step is to set up our environment:

```{r}
# devtools::install_github("vegawidget/altair")
library("altair")
library("tibble")

vega_data <- import_vega_data()
```

## Binned Movie Rating Heatmap

#### Data

```{r}
glimpse(vega_data$movies())
```

#### Chart

```{r}
chart <- 
  alt$Chart(r_to_py(vega_data$movies()))$
  mark_rect()$
  encode(
    x = alt$X("IMDB_Rating:Q", bin = alt$Bin(maxbins = 60)),
    y = alt$Y("Rotten_Tomatoes_Rating:Q", bin=alt$Bin(maxbins = 40)),
    color = alt$Color(
      "count(IMDB_Rating):Q", 
      scale = alt$Scale(scheme = "greenblue")
    )
  )

chart
```

## Facetted Scatterplot with marginal histograms

#### Data

```{r}
glimpse(vega_data$iris())
```

#### Chart

```{r}
iris <- r_to_py(vega_data$iris())

xscale <- alt$Scale(domain = list(4.0, 8.0))
yscale <- alt$Scale(domain = list(1.9, 4.55))

blank_axis <- alt$Axis(title = "")

points <- 
  alt$Chart(iris)$
  mark_circle()$
  encode(
    alt$X("sepalLength", scale = xscale),
    alt$Y("sepalWidth", scale = yscale),
    color = "species"
  )

top_hist <-
  alt$Chart(iris)$
  mark_area(opacity = 0.3, interpolate = "step")$
  encode(
    x = alt$X("sepalLength:Q",
          # when using bins, the axis scale is set through
          # the bin extent, so we do not specify the scale here
          # (which would be ignored anyway)
          bin = alt$Bin(maxbins = 20, extent = xscale$domain),
          stack = NULL,
          axis = blank_axis
        ),
    y = alt$Y("count(sepalLength)", stack = NULL, axis = blank_axis),
    color = alt$Color("species:N")
  )$
  properties(height=60)

right_hist <- 
  alt$Chart(iris)$
  mark_area(opacity= 0.3, interpolate= "step")$
  encode(
    x = alt$X("count(sepalWidth)", stack=NULL, axis=blank_axis),
    y = alt$Y(
      "sepalWidth:Q",
      bin = alt$Bin(maxbins = 20, extent = yscale$domain),
      stack = NULL,
      axis = blank_axis
    ),
    color = alt$Color("species:N")
  )$
  properties(width=60)

chart <- (top_hist & (points | right_hist))

chart
```

## Layering text over a heatmap

#### Data

```{r}
glimpse(vega_data$cars())
```

#### Chart

```{r}
cars <- r_to_py(vega_data$cars())

heatmap <- 
  alt$Chart(cars)$
  mark_rect()$
  encode(
    x = alt$X("Cylinders:O", scale = alt$Scale(paddingInner = 0)),
    y = alt$Y("Origin:O", scale = alt$Scale(paddingInner = 0)),
    color= "count(Cylinders)"
  )

text <- 
  alt$Chart(cars)$
  mark_text(baseline="middle")$
  encode(
    x = "Cylinders:O",
    y = "Origin:O",
    text = "count(Cylinders)",
    color = alt$condition(
      "datum['count_*'] > 100",
      alt$value("black"),
      alt$value("white")
    )
  )

chart <- (heatmap + text)

chart
```

#### Multiple Marks (not working)


#### Data

```{r}
glimpse(vega_data$stocks())
```

#### Chart

```{r, eval = FALSE}
stocks <- r_to_py(vega_data$stocks())

chart <- 
  alt$LayerChart(stocks)$
  encode(
    x = "date:T",
    y = "price:Q",
    color = "symbol:N"
  )$add_layers(
    alt$Chart()$mark_point(),
    alt$Chart()$mark_line()
  )

chart
```

#### Ranged Dot Plot

#### Steam and Leaf Plot

#### Trail Marker







