#' Vega embed options
#'
<<<<<<< HEAD
#' @param mode `character` if specified, tells Vega-Embed to parse the spec
#'   as vega or vega-lite. Vega-Embed will parse the `$schema` url if the mode
#'   is not specified. Vega-Embed will default to vega if neither mode,
#'   nor $schema are specified.
#' @param renderer `character` the renderer to use for the view.
#'   One of `"canvas"` (default) or `"svg"`.
#'   See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_renderer)
#'   for details.
#' @param logLevel 	sets the current log level.
#'  See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_logLevel)
#'  for details.
#' @param loader	sets a custom Vega loader.
#'   See [Vega docs](https://github.com/vega/vega-loader#loader)
#'   for details.
#' @param onBeforeParse	`JS` function, modifies the spec before being parsed.
#' @param width	`integer` sets the view width in pixels.
#' See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_width)
#' for details.
#' Note that Vega-Lite overrides this option.
#' @param height	`integer`, sets the view height in pixels.
#' See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_height)
#' for details.
#' Note that Vega-Lite overrides this option.
#' @param padding	`list`, sets the view padding in pixels.
#' See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_padding)
#' for details.
#' @param actions `logical` or `list`, determines if action links
#'   ("Export as PNG/SVG", "View Source", "Open in Vega Editor")
#'   are included with the embedded view.
#'   If the value is `TRUE` (default), all action links will be shown
#'   and none if the value is `FALSE`. This property can be a list that maps
#'   keys (`export`, `source`, `editor`) to logical values for determining
#'   if each action link should be shown. Unspecified keys will be true by
#'   default. For example, if `actions` is
#'   `list(export =  FALSE, source = TRUE)`, the embedded visualization will
#'   have two links – "View Source" and "Open in Vega Editor".
#' @param config `character` or `list` a URL string** from which to load
#'   a Vega/Vega-Lite or Vega-Lite configuration file, or a `list` of
#'   Vega/Vega-Lite configurations to override the default configuration
#'   options.
#' @param editorUrl	`character`, URL at which to open embedded Vega specs
#'   in a Vega editor. Defaults to `"http://vega.github.io/editor/"`.
#'   Internally, Vega-Embed uses
#'   [HTML5 postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)
#'   to pass the specification information to the editor.
#' @param sourceHeader `character`, HTML to inject into the `` tag of the
#'   page generated by the "View Source" action link. For example, this
#'   can be used to add code for [syntax highlighting](https://highlightjs.org/).
#' @param sourceFooter `character`, HTML to inject into the end of the
#'   page generated by the "View Source" action link. The text will be added
#'   immediately before the closing `` tag.
#' @param runAsync	`logical`, use
#'   [`runAsync`](https://vega.github.io/vega/docs/api/view/#view_runAsync)
#'   instead of [`run`](https://vega.github.io/vega/docs/api/view/#view_run).
=======
#' @param actions `logical` or `list` of logicals
#'   Vega-Embed default is all TRUE.
>>>>>>> 54d68646fa8b19cf28e2f2a81fc9b6b49120dbf8
#'
#' @return `list`
#' @export
#'
vega_embed <- function(actions = TRUE) {

  embed_options <-
    list(
      actions = actions
    )

  embed_options
}
