#' Vega embed options
#'
#' Use this function to specify embedding-options to the vegalite renderer.
#' The most common options to set are `renderer`, to specify `"canvas"`
#' or `"svg"`, and `actions`, to specify the inclusion of `export`, `source`,
#' and `editor` links. This documentation is adapted from the
#' [vega-embed documentation](https://github.com/vega/vega-embed#options).
#'
#' The default `renderer` is `"canvas"`.
#'
#' The default for `actions` is `TRUE`, which means that all three action links
#' will be included.
#'
#' - To suppress all action links, call with `actions = FALSE`.
#' - To suppress a given action link, call with a list:
#'   `actions = list(editor = FALSE)`.
#' - To specify which link(s) to include, call using the `only_actions()`
#'   function: `actions = only_actions(export = TRUE)`.
#'
#' It is ineffective to set the `width` and `height` parameters here, as they
#' will be overridden by the values in the chart specification.
#'
#'
#' @param mode `character` if specified, tells Vega-Embed to parse the spec
#'   as vega or vega-lite. Vega-Embed will parse the `$schema` url if the mode
#'   is not specified. Vega-Embed will default to vega if neither mode,
#'   nor $schema are specified.
#' @param renderer `character` the renderer to use for the view.
#'   One of `"canvas"` (default) or `"svg"`.
#'   See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_renderer)
#'   for details.
#' @param logLevel 	sets the current log level.
#'  See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_logLevel)
#'  for details.
#' @param loader	sets a custom Vega loader.
#'   See [Vega docs](https://github.com/vega/vega-loader#loader)
#'   for details.
#' @param onBeforeParse	`JS` function, modifies the spec before being parsed.
#' @param width	`integer` sets the view width in pixels.
#' See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_width)
#' for details.
#' Note that Vega-Lite overrides this option.
#' @param height	`integer`, sets the view height in pixels.
#' See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_height)
#' for details.
#' Note that Vega-Lite overrides this option.
#' @param padding	`list`, sets the view padding in pixels.
#' See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_padding)
#' for details.
#' @param actions `logical` or named vector of logicals, determines if action links
#'   ("Export as PNG/SVG", "View Source", "Open in Vega Editor")
#'   are included with the embedded view.
#'   If the value is `TRUE` (default), all action links will be shown
#'   and none if the value is `FALSE`. This property can be a named vector of
#'   logicals that maps
#'   keys (`export`, `source`, `editor`) to logical values for determining
#'   if each action link should be shown. Unspecified keys will be true by
#'   default. For example, if `actions` is
#'   `list(export =  FALSE, source = TRUE)`, the embedded visualization will
#'   have two links – "View Source" and "Open in Vega Editor".
#' @param config `character` or `list` a URL string** from which to load
#'   a Vega/Vega-Lite or Vega-Lite configuration file, or a `list` of
#'   Vega/Vega-Lite configurations to override the default configuration
#'   options. If `config` is a URL, it will be subject to standard browser
#'   security restrictions. Typically this URL will point to a file on the same
#'   host and port number as the web page itself.
#' @param editorUrl	`character`, URL at which to open embedded Vega specs
#'   in a Vega editor. Defaults to `"http://vega.github.io/editor/"`.
#'   Internally, Vega-Embed uses
#'   [HTML5 postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)
#'   to pass the specification information to the editor.
#' @param sourceHeader `character`, HTML to inject into the `` tag of the
#'   page generated by the "View Source" action link. For example, this
#'   can be used to add code for [syntax highlighting](https://highlightjs.org/).
#' @param sourceFooter `character`, HTML to inject into the end of the
#'   page generated by the "View Source" action link. The text will be added
#'   immediately before the closing `` tag.
#' @param runAsync	`logical`, indicating to use
#'   [`runAsync`](https://vega.github.io/vega/docs/api/view/#view_runAsync)
#'   instead of [`run`](https://vega.github.io/vega/docs/api/view/#view_run).
#'
#' @seealso [vegawidget()], [only_actions()]
#' @examples
#' # Set the renderer
#' embed_options <- vega_embed(renderer = "svg")
#'
#' # Specify the action links
#' embed_options <- vega_embed(actions = FALSE)
#' embed_options <- vega_embed(actions = list(editor = FALSE))
#' embed_options <- vega_embed(actions = only_actions(export = TRUE))
#'
#' @return S3 object with class `vega_embed`
#' @export
#'
vega_embed <- function(renderer = c("canvas", "svg"),
                       actions = TRUE,
                       mode = NULL,
                       logLevel = NULL,
                       loader = NULL,
                       onBeforeParse = NULL,
                       width = NULL,
                       height = NULL,
                       padding = NULL,
                       config = NULL,
                       editorUrl = NULL,
                       sourceHeader = NULL,
                       sourceFooter = NULL,
                       runAsync = NULL) {

  renderer <- match.arg(renderer)

  # coerce actions to logical, preserve names
  names_actions <- names(actions)
  actions <- as.logical(actions)

  # if named, turn into a list
  if (!is.null(names_actions)) {
    actions <- as.list(actions)
    names(actions) <- names_actions
  }

  names_actions_legal <- c("export", "source", "editor")

  # unnamed must have length 1
  if (!rlang::is_named(actions)) {
    assertthat::assert_that(
      identical(length(actions), 1L),
      msg = ("if `actions` is unnamed, it must have length 1")
    )
  }

  # names have to be unique and proper
  if (rlang::is_named(actions)) {
    assertthat::assert_that(identical(names_actions, unique(names_actions)))
    assertthat::assert_that(
      all(names_actions %in% names_actions_legal),
      msg = paste(
        "`actions` has illegal name",
        paste("provided names:", paste(names_actions, collapse = ", ")),
        paste("legal names:", paste(names_actions_legal, collapse = ", ")),
        sep = "\n"
      )
    )
  }

  options <-
    list(
      mode = mode,
      renderer = renderer,
      logLevel = logLevel,
      loader = loader,
      onBeforeParse = onBeforeParse,
      width = width,
      height = height,
      padding = padding,
      actions = actions,
      config = config,
      editorUrl = editorUrl,
      sourceHeader = sourceHeader,
      sourceFooter = sourceFooter,
      runAsync = runAsync
    )

  embed_options <-
    structure(
      list_remove_null(options),
      class = "vega_embed"
    )

  embed_options
}

#' Helper function for vega_embed actions
#'
#' This function can be useful if you want to specify only one
#' of the links include in the embedding-options.
#'
#' @param export `logical`, include "Export As ..." link
#' @param source `logical`, include "View Source" link
#' @param editor `logical`, include "Open in Vega Editor" link
#'
#' @return `list`
#' @export
#'
only_actions = function(export = FALSE, source = FALSE, editor = FALSE) {
  list(
    export = as.logical(export),
    source = as.logical(source),
    editor = as.logical(editor)
  )
}
